### ISSUE TITLE
Popup slightly too far left

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/IOT-Map-Component#17]
With iotmapmanager version 2.0.1, the popups are slightly too far left.

Observed with Firefox and Chrome.

![Capture d’écran 2021-03-30 à 14 36 19](https://user-images.githubusercontent.com/17381666/112989706-7d02ec00-9165-11eb-816c-82790ae87353.png)

In `popup.css`, the rule is : 
```css
.marker-selected > .marker-popup {
  left: -100px
}
```

It would rather work for me with `left: -85px` or `width` set to something like `240px` 🤷
